/**
 * Static dataset loader for the app and tests.
 * Reads src/data/*.json (generated by scripts/convert_data.py from research/data/).
 */
import type { Dataset, WhoTable, WhsDigitizedRow } from "./types.js";
import { buildWhsIndex, type WhsIndex } from "./whs.js";
import wfaBoys from "../data/who_lms/wfa_boys.json";
import wfaGirls from "../data/who_lms/wfa_girls.json";
import lhfaBoys from "../data/who_lms/lhfa_boys.json";
import lhfaGirls from "../data/who_lms/lhfa_girls.json";
import wflBoys from "../data/who_lms/wfl_boys.json";
import wflGirls from "../data/who_lms/wfl_girls.json";
import wfhBoys from "../data/who_lms/wfh_boys.json";
import wfhGirls from "../data/who_lms/wfh_girls.json";
import whsData from "../data/whs_digitized.json";

export function loadDataset(): Dataset {
  const who: Record<string, WhoTable> = {
    wfa_boys: wfaBoys as unknown as WhoTable,
    wfa_girls: wfaGirls as unknown as WhoTable,
    lhfa_boys: lhfaBoys as unknown as WhoTable,
    lhfa_girls: lhfaGirls as unknown as WhoTable,
    wfl_boys: wflBoys as unknown as WhoTable,
    wfl_girls: wflGirls as unknown as WhoTable,
    wfh_boys: wfhBoys as unknown as WhoTable,
    wfh_girls: wfhGirls as unknown as WhoTable,
  };
  const whs = (whsData as unknown as { rows: WhsDigitizedRow[] }).rows;
  return { who, whs };
}

export function loadContext(): { dataset: Dataset; whs: WhsIndex } {
  const dataset = loadDataset();
  return { dataset, whs: buildWhsIndex(dataset.whs) };
}
